# Generated by Django 3.1.1 on 2020-09-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20200906_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='city',
            name='pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='temperature_feel',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
